### ISSUE TITLE
NewLine character \n is escaped with one more slash

### ISSUE THREAD

**Issue by htqbuu** [defuncart/arb_generator#6]
Hi,

Thanks for the package. However, I cannot print character "\n" from csv to arb string. The result comes out to "\\\\n".
For example, I have a string in csv cell like "This is \n new line". The result arb string will be "This is \\\\n new line".

Am I missing something?

Thanks

**Comment by defuncart** [comment]
Hi @htqbuu, thanks for the bug report, I can easily reproduce this in the example project. The problem seems to stem from [formatting the arb file](https://github.com/defuncart/arb_generator/blob/main/lib/src/services/arb_generator.dart#L65). This seems to be a quick fix:

```dart
var prettyContent = encoder.convert(content.toJson());
prettyContent = prettyContent.replaceAll('\\\\', '\\');
```

I'll do some tests over the coming days to see if there are any side effects, if not a push a new release.

In the meantime, you can update pubspec to use a branch from this repo:

```yaml
arb_generator:
    git:
      url: https://github.com/defuncart/arb_generator.git
      ref: bugfix/ensure-escaped-characters-are-correct
```
